/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdWaitingRouteImport } from './routes/room.$roomId.waiting'
import { Route as RoomRoomIdPlayRouteImport } from './routes/room.$roomId.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdWaitingRoute = RoomRoomIdWaitingRouteImport.update({
  id: '/room/$roomId/waiting',
  path: '/room/$roomId/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdPlayRoute = RoomRoomIdPlayRouteImport.update({
  id: '/room/$roomId/play',
  path: '/room/$roomId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$roomId/play': typeof RoomRoomIdPlayRoute
  '/room/$roomId/waiting': typeof RoomRoomIdWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$roomId/play': typeof RoomRoomIdPlayRoute
  '/room/$roomId/waiting': typeof RoomRoomIdWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$roomId/play': typeof RoomRoomIdPlayRoute
  '/room/$roomId/waiting': typeof RoomRoomIdWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomId/play' | '/room/$roomId/waiting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomId/play' | '/room/$roomId/waiting'
  id: '__root__' | '/' | '/room/$roomId/play' | '/room/$roomId/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomIdPlayRoute: typeof RoomRoomIdPlayRoute
  RoomRoomIdWaitingRoute: typeof RoomRoomIdWaitingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/waiting': {
      id: '/room/$roomId/waiting'
      path: '/room/$roomId/waiting'
      fullPath: '/room/$roomId/waiting'
      preLoaderRoute: typeof RoomRoomIdWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/play': {
      id: '/room/$roomId/play'
      path: '/room/$roomId/play'
      fullPath: '/room/$roomId/play'
      preLoaderRoute: typeof RoomRoomIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomIdPlayRoute: RoomRoomIdPlayRoute,
  RoomRoomIdWaitingRoute: RoomRoomIdWaitingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
